# Generated by Django 5.1.1 on 2024-10-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_comment_options'),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['date_time_of_publication'], name='common_comm_date_ti_d3f02d_idx'),
        ),
    ]
