# Generated by Django 5.1.1 on 2024-10-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_pet_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='pet_photo',
            new_name='personal_photo',
        ),
        migrations.AlterField(
            model_name='pet',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
